osx_image: xcode7.3
language: objective-c
script:
    - |
      xcodebuild test \
      -project LeetCode-Swift/LeetCode-Swift.xcodeproj \
      -scheme LeetCode-SwiftTests \
      -sdk iphonesimulator \
      ONLY_ACTIVE_ARCH=NO
